"""End-to-end smoke tests: one happy-path per resource mixin.

The 24 endpoint methods on `SendbeeApi` are all generated by `bind_request`,
which is covered in detail elsewhere. These tests verify the wiring per mixin
- that each `bind_request(...)` call site declares the right `api_path`,
`method`, `model`, and `QueryParams` - by exercising one representative
endpoint per mixin through a mocked HTTP response.
"""

import responses
import ujson

from sendbee_api.contacts.models import Contact
from sendbee_api.conversations.models import Conversation, SentMessage
from sendbee_api.automation.models import ChatbotActivityStatus
from sendbee_api.teams.models import Team
from sendbee_api.rate_limit.models import RateLimitError
from sendbee_api.models import ServerMessage


@responses.activate
def test_contacts_list_endpoint_returns_contact_models(client, register, json_body):
    """SendbeeApi.contacts() hits /contacts and parses Contact models."""
    register("GET", "/contacts", body=json_body(
        data=[{
            "id": "c1",
            "name": "Alice",
            "phone": "+1234",
            "status": "subscribed",
            "tags": [],
            "contact_fields": [],
            "notes": [],
        }],
        meta={"current_page": 1, "last_page": 1, "total": 1},
    ))

    response = client.contacts()

    assert "/contacts" in responses.calls[0].request.url
    assert responses.calls[0].request.method == "GET"
    assert len(response.models) == 1
    contact = response.models[0]
    assert isinstance(contact, Contact)
    assert contact.id == "c1"
    assert contact.name == "Alice"


@responses.activate
def test_conversations_list_endpoint_returns_conversation_models(client, register, json_body):
    """SendbeeApi.conversations() hits /conversations and parses Conversation models."""
    register("GET", "/conversations", body=json_body(
        data=[{
            "id": "conv1",
            "folder": "open",
            "chatbot_active": True,
            "platform": "whatsapp",
            "contact": {"id": "c1", "name": "Alice", "phone": "+1234"},
            "last_message": {
                "direction": "inbound",
                "status": "delivered",
                "inbound_sent_at": None,
                "outbound_sent_at": None,
            },
        }],
        meta={"current_page": 1, "last_page": 1, "total": 1},
    ))

    response = client.conversations()

    assert "/conversations" in responses.calls[0].request.url
    assert isinstance(response.models[0], Conversation)
    assert response.models[0].id == "conv1"
    assert response.models[0].contact.name == "Alice"


@responses.activate
def test_send_message_post_endpoint_returns_single_sent_message(client, register, json_body):
    """send_message is a POST that returns one SentMessage, not a Response."""
    register("POST", "/conversations/messages/send", body=json_body(
        data=[{
            "id": "conv1",
            "message_id": "msg1",
            "message_reference_id": "ref1",
            "status": "queued",
        }],
        meta={"current_page": 1, "last_page": 1},
    ))

    result = client.send_message(phone="+1234", text="hello")

    assert isinstance(result, SentMessage)
    assert result.message_id == "msg1"
    assert responses.calls[0].request.method == "POST"
    body = ujson.loads(responses.calls[0].request.body)
    assert body == {"phone": "+1234", "text": "hello"}


@responses.activate
def test_chatbot_activity_status_endpoint_returns_single_status_model(client, register, json_body):
    """chatbot_activity_status is force-single-model GET; returns one model."""
    register("GET", "/automation/chatbot/activity/status", body=json_body(
        data=[{"conversation_id": "conv1", "chatbot_active": True}],
        meta={"current_page": 1, "last_page": 1},
    ))

    result = client.chatbot_activity_status(conversation_id="conv1")

    assert isinstance(result, ChatbotActivityStatus)
    assert result.conversation_id == "conv1"
    assert result.chatbot_active is True


@responses.activate
def test_teams_list_endpoint_returns_team_models(client, register, json_body):
    """SendbeeApi.teams() hits /teams/teams and parses Team models."""
    register("GET", "/teams/teams", body=json_body(
        data=[{"id": "t1", "name": "Support", "members": []}],
        meta={"current_page": 1, "last_page": 1, "total": 1},
    ))

    response = client.teams()

    assert "/teams/teams" in responses.calls[0].request.url
    assert isinstance(response.models[0], Team)
    assert response.models[0].name == "Support"


@responses.activate
def test_rate_limit_error_test_endpoint_returns_rate_limit_error_model(client, register, json_body):
    """rate_limit_error_test hits /rate-limit/error-test on the RateLimit mixin."""
    register("GET", "/rate-limit/error-test", body=json_body(
        data=[{"detail": "Too many", "error": True, "type": "rate_limit"}],
        meta={"current_page": 1, "last_page": 1},
    ))

    response = client.rate_limit_error_test()

    assert "/rate-limit/error-test" in responses.calls[0].request.url
    assert isinstance(response.models[0], RateLimitError)
    assert response.models[0].detail == "Too many"


@responses.activate
def test_delete_tag_returns_server_message_ack(client, register, json_body):
    """delete_tag is a DELETE; response is a ServerMessage ack."""
    register("DELETE", "/contacts/tags", body=json_body(
        data=[{"message": "tag deleted"}],
        meta={"current_page": 1, "last_page": 1},
    ))

    result = client.delete_tag(id="tag-uuid-1")

    assert isinstance(result, ServerMessage)
    assert result.message == "tag deleted"
    assert responses.calls[0].request.method == "DELETE"


@responses.activate
def test_subscribe_contact_default_parameters_block_automation_and_notifications(
    client, register, json_body
):
    """subscribe_contact's bind-site defaults set block_automation=block_notifications=True."""
    register("POST", "/contacts/subscribe", body=json_body(
        data=[{
            "id": "c1", "name": "Alice", "phone": "+1234",
            "status": "subscribed", "tags": [], "contact_fields": [], "notes": [],
        }],
        meta={"current_page": 1, "last_page": 1},
    ))

    client.subscribe_contact(phone="+1234", name="Alice")

    body = ujson.loads(responses.calls[0].request.body)
    assert body["block_automation"] is True
    assert body["block_notifications"] is True
    assert body["phone"] == "+1234"
    assert body["name"] == "Alice"
